import React from "react";
import { Typography, Grid, Card, CardContent, CardMedia, Button, CardActions, Box } from "@mui/material";
import OpenInNewIcon from "@mui/icons-material/OpenInNew";

export default function NewsSection({ title, articles }) {
  if (!articles || articles.length === 0) return null;

    return (
        <Box sx={{ mb: 4 }}>
              <Typography variant="h5" fontWeight={700} gutterBottom sx={{ mt: 2, mb: 2 }}>
                      {title}
                            </Typography>
                                  <Grid container spacing={3}>
                                          {articles.map((article, idx) => (
                                                    <Grid item xs={12} sm={6} key={idx}>
                                                                <Card sx={{ height: "100%", display: "flex", flexDirection: "column" }}>
                                                                              {article.urlToImage && (
                                                                                              <CardMedia
                                                                                                                component="img"
                                                                                                                                  height="160"
                                                                                                                                                    image={article.urlToImage}
                                                                                                                                                                      alt={article.title}
                                                                                                                                                                                      />
                                                                                                                                                                                                    )}
                                                                                                                                                                                                                  <CardContent>
                                                                                                                                                                                                                                  <Typography gutterBottom variant="h6" component="h3" fontWeight={600}>
                                                                                                                                                                                                                                                    {article.title}
                                                                                                                                                                                                                                                                    </Typography>
                                                                                                                                                                                                                                                                                    <Typography variant="body2" color="text.secondary" sx={{ mb: 1 }}>
                                                                                                                                                                                                                                                                                                      {article.description}
                                                                                                                                                                                                                                                                                                                      </Typography>
                                                                                                                                                                                                                                                                                                                                      <Typography variant="caption" color="text.secondary">
                                                                                                                                                                                                                                                                                                                                                        {article.source?.name} {article.publishedAt && `- ${new Date(article.publishedAt).toLocaleDateString("pt-BR")}`}
                                                                                                                                                                                                                                                                                                                                                                        </Typography>
                                                                                                                                                                                                                                                                                                                                                                                      </CardContent>
                                                                                                                                                                                                                                                                                                                                                                                                    <CardActions>
                                                                                                                                                                                                                                                                                                                                                                                                                    <Button
                                                                                                                                                                                                                                                                                                                                                                                                                                      size="small"
                                                                                                                                                                                                                                                                                                                                                                                                                                                        color="primary"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          href={article.url}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            target="_blank"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              endIcon={<OpenInNewIcon />}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Ler mais
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </CardActions>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </Card>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </Grid>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </Grid>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </Box>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }